spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
    alicloud:
      access-key: ab
      secret-key: ab
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: mall-imilia
  application:
    name: mall-third-party

server:
  port: 30000
